version: '3.1'

services:
  db:
    image: mysql:5.7.31
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_USER: wordpress
    ports:
      - 9002:3306
    volumes:
      - ./data/mysql:/var/lib/mysql

  wordpress:
    image: wordpress:5.5.0-php7.4-apache
    restart: unless-stopped
    env_file: .env
    ports:
      - 9001:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
      WORDPRESS_CONFIG_EXTRA: "define('FS_METHOD', 'direct');"
    volumes:
      - ./data/wordpress:/var/www/html

